version: '3.7'

services:
  # Node.js
  node:
    image: 'node:11-alpine'
    environment:
      NODE_ENV: docker
    volumes:
      - './:/var/www/einsamkeit'
    ports:
      - '3000:3000'
    user: 'node'
    working_dir: /var/www/einsamkeit
    command: 'npm run server:web'

  # PostgreSQL
  postgres:
    image: 'postgres:11-alpine'
    environment:
      POSTGRES_USER: 'einsamkeit'
      POSTGRES_PASSWORD: 'loneliness'
      POSTGRES_DB: 'einsamkeit'
    volumes:
      - './docker/data/postgres:/var/lib/postgresql/data'
    expose:
      - '5432'

  # Redis
  redis:
    image: 'redis:5-alpine'
    expose:
      - '6379'
