version: '3.7'

services:
  # Web server
  node_web:
    image: 'node:11-alpine'
    environment:
      NODE_ENV: docker
    volumes:
      - './:/var/www/einsamkeit'
      - './docker/etc/:/etc/einsamkeit'
    networks:
      - 'kodoku'
    ports:
      - '4000:4000'
    user: 'node'
    working_dir: /var/www/einsamkeit
    command: 'npm run server:web'

  # Job worker
  node_worker:
    image: 'node:11-alpine'
    environment:
      NODE_ENV: docker
    volumes:
      - './:/var/www/einsamkeit'
      - './docker/etc/:/etc/einsamkeit'
    networks:
      - 'kodoku'
    user: 'node'
    working_dir: /var/www/einsamkeit
    command: 'npm run server:queue'

  # PostgreSQL
  postgres:
    image: 'postgres:11-alpine'
    environment:
      POSTGRES_USER: 'einsamkeit'
      POSTGRES_PASSWORD: 'loneliness'
      POSTGRES_DB: 'einsamkeit'
    volumes:
      - './docker/data/postgres:/var/lib/postgresql/data'
      - './docker/etc/:/etc/einsamkeit'
    networks:
      - 'kodoku'
    expose:
      - '5432'

  # Redis
  redis:
    image: 'redis:5-alpine'
    volumes:
      - './docker/etc/:/etc/einsamkeit'
      - './docker/data/redis/:/data'
    networks:
      - 'kodoku'
    expose:
      - '6379'

networks:
  kodoku:
    driver: 'bridge'
    ipam:
      driver: 'default'
      config:
        - subnet: '172.31.0.0/24'
